AWSTemplateFormatVersion: 2010-09-09
Description: Create SSM Parameters of the Instance for IAM Identity Center.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: System Configuration
        Parameters:
          - Stack
          - Env
      -
        Label:
          default: ParamTest Configuration
        Parameters:
          - ParamTest

Parameters: 
  ParamTest:
    Description: ParamTest.
    Type: String

  Stack:
    Description: Type the Name for Stack Tag.
    Type: String
    Default: multi-account-infra
    AllowedPattern: ^[a-z][a-z0-9\-]{1,}[a-z0-9]$

  Env:
    Description: Type the Name for Env Tag. 
    Type: String
    Default: common
    AllowedValues:
      - prod
      - stage
      - test
      - dev
      - common

Conditions:
  CreateParam:
    !Not [!Equals ['', !Ref ParamTest]]

Resources: 
#------------------------------------#
# SSM Parameter
#------------------------------------#
  SSMParamParamTest:
    Condition: CreateParam
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /${Env}/test
      Type: String
      Value: !Ref ParamTest
      Tags:
        Stack: !Ref Stack
        Env: !Ref Env
        Name: !Sub ${Stack}-${Env}