AWSTemplateFormatVersion: "2010-09-09"
Description: Provides frontend base.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: System Configuration
        Parameters:
          - Env
          - Stack
          - Owner

    ParameterLabels:
      Stack:
        default: 'Stack: *Only lowercase alphanumeric characters and hyphens are allowed.'
      Owner:
        default: 'Owner: *Only lowercase alphanumeric characters and hyphens are allowed. Please put a hyphen between your first name and last name.'

Parameters:
  Env:
    Description: Specify the Env Tag. 
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - stage
      - test
      - dev
      - common

  Stack:
    Description: Specify the Stack Tag.
    Type: String
    Default: network
    AllowedPattern: ^[a-z]([\-]{0,1}[a-z0-9]+)*$
    ConstraintDescription: This Parameter must match pattern ^[a-z]([\-]{0.1}[a-z0-9]+)*$

  Owner:
    Description: Enter the name of the person creating this stack.
    Type: String
    Default: masaki-ishimoto
    AllowedPattern: ^[a-z]([\-]{0,1}[a-z0-9]+)*$
    ConstraintDescription: This Parameter must match pattern ^[a-z]([\-]{0.1}[a-z0-9]+)*$

  IdVpc:
    Description : Specify the VPC ID.
    Type: AWS::EC2::VPC::Id

  IdSecurityGroupInternet:
    Description:  Specify the ID of the InternetSecurityGroup for ALB.
    Type: AWS::EC2::SecurityGroup::Id

  IdSubnetPublicIngress1A:
    Description: Specify the ID of the IngressPublicSubnet1A for ALB.
    Type: AWS::EC2::Subnet::Id

  IdSubnetPublicIngress1C:
    Description: Specify the ID of the IngressPublicSubnet1C for ALB.
    Type: AWS::EC2::Subnet::Id
    
  DnsAlbBackend:
    Description: Specify the DNS A record of the Backend ALB.
    Type: String

  NameFrontendContainer:
    Description: Enter the Name for Frontend Container.
    Type: String
    Default: frontend-app
  
  PortFrontendContainer:
    Description: Specify the Port Number for Frontend Container.
    Type: String
    Default: 80

  ArnTargetGroupBlue:
    Description: Specify the ARN of the TargetGroupBlue.
    Type: String

  ArnTargetGroupGreen:
    Description: Specify the ARN of the TargetGroupGreen.
    Type: String

  IdSecurityGroupBackendContainer:
    Description: Specify the ID of the BackendContainerSecurityGroup.
    Type: AWS::EC2::SecurityGroup::Id
  
  IdSubnetPrivateContainer1A:
    Description: Specify the ID of the ContainerPrivateSubnet1A for Container.
    Type: AWS::EC2::Subnet::Id

  IdSubnetPrivateContainer1C:
    Description: Specify the ID of the ContainerPrivateSubnet1C for Container.
    Type: AWS::EC2::Subnet::Id
    
Resources:
#-----------------------------------#
# ECS
#-----------------------------------#

  ClusterFrontend:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders:
        - FARGATE
      ClusterName: !Sub ${Env}-${Stack}-frontend-cluster
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Env
          Value: !Ref Env
        - Key: Stack
          Value: !Ref Stack
        - Key: Owner
          Value: !Ref Owner

  ServiceFrontend:
    Type: AWS::ECS::Service
    Properties: 
      CapacityProviderStrategy: 
        - Base: 2
          CapacityProvider: FARGATE
          Weight: 1
        - Base: 0
          CapacityProvider: FARGATE_SPOT
          Weight: 1
      Cluster: !GetAtt ClusterFrontend.Arn
      DeploymentController: CODE_DEPLOY
      DesiredCount: 2
      EnableECSManagedTags: true
      EnableExecuteCommand: false ######
      HealthCheckGracePeriodSeconds: 120
      LaunchType: FARGATE
      LoadBalancers: 
        - ContainerName: !Ref NameFrontendContainer
          ContainerPort: !Ref PortFrontendContainer
          TargetGroupArn: !Ref ArnTargetGroupBlue
        - ContainerName: !Ref NameFrontendContainer
          ContainerPort: !Ref PortFrontendContainer
          TargetGroupArn: !Ref ArnTargetGroupGreen
      NetworkConfiguration: 
        AwsvpcConfiguration:
          AssignPublicIp: DISABLE
          SecurityGroups:
            - !Ref IdSecurityGroupBackendContainer
          Subnets:
            - !Ref IdSubnetPrivateContainer1A
            - !Ref IdSubnetPrivateContainer1C
      # PlacementConstraints: 
      #   - PlacementConstraint
      # PlacementStrategies: 
      #   - PlacementStrategy
      PlatformVersion: 1.4.0
      PropagateTags: NONE
      SchedulingStrategy: REPLICA
      ServiceName: ecs-frontend-service
      ServiceRegistries: 
        - !GetAtt ServiceDiscovery.Arn ####
      TaskDefinition: !Ref TaskDefinitionFrontend
      Tags:
        - Key: Env
          Value: !Ref Env
        - Key: Stack
          Value: !Ref Stack
        - Key: Owner
          Value: !Ref Owner

  TaskDefinitionFrontend:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${Env}-${Stack}-frontend-task-definition
      ContainerDefinitions:
        - 
          Name: !Ref NameFrontendContainer
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/sbcntr-frontend:v1"
          Essential: true
          Cpu: 256
          MemoryReservation: 512
          ReadonlyRootFilesystem: true
          PortMappings:
            - ContainerPort: !Ref PortFrontendContainer
              HostPort: 80
              Protocol: tcp
          Environment:
            - Name: SESSION_SECRET_KEY
              Value: 41b678c65b37bf99c37bcab522802760
            - Name: APP_SERVICE_HOST
              Value: !Sub "http://${DnsAlbBackend}"
            - Name: NOTIF_SERVICE_HOST
              Value: !Sub "http://${DnsAlbBackend}"
          LogConfiguration:
              LogDriver: awslogs
              Options: 
                awslogs-group: !Sub "/ecs/${Env}-${Stack}-frontend-def"
                awslogs-region: !Ref AWS::Region
                awslogs-stream-Stack: ecs
      Cpu: 512
      Memory: 1024
      ExecutionRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Tags:
        - Key: Env
          Value: !Ref Env
        - Key: Stack
          Value: !Ref Stack
        - Key: Owner
          Value: !Ref Owner

  CloudWatchLogsFrontend:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Retain
    Properties:
      LogGroupName: /ecs/sbcntr-frontend-def
      RetentionInDays: 14
      Tags:
        - Key: Env
          Value: !Ref Env
        - Key: Stack
          Value: !Ref Stack
        - Key: Owner
          Value: !Ref Owner

#-----------------------------------#
# ServiceDiscovery (Cloud Map)
#-----------------------------------#
  ServiceDiscovery:
    Type: AWS::ServiceDiscovery::Service
    Properties:
      Name: ecs-backend-service
      Description: 'Service Discovery for ECS.'
      DnsConfig:
        DnsRecords:
          - Type: A
            TTL: 60
        NamespaceId: !GetAtt ServiceDiscoveryPrivateDnsNamespace.Id
      # HealthCheckConfig:
      #   FailureThreshold: String
      #   ResourcePath: "String"
      #   Type: "String"
      # HealthCheckCustomConfig:
      #   FailureThreshold: String
      Tags:
        - Key: Env
          Value: !Ref Env
        - Key: Stack
          Value: !Ref Stack
        - Key: Owner
          Value: !Ref Owner

  ServiceDiscoveryPrivateDnsNamespace:
    Type: AWS::ServiceDiscovery::PrivateDnsNamespace
    Properties: 
      Description: 'Service Discovery for ECS'
      Name: local
      # Properties: 
      #   DnsProperties:
      #     SOA:
      #       TTL: 60            
      Vpc: !Ref IdVpc
      Tags:
        - Key: Env
          Value: !Ref Env
        - Key: Stack
          Value: !Ref Stack
        - Key: Owner
          Value: !Ref Owner

#-----------------------------------#
# ALB
#-----------------------------------#
  AlbFrontend:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub "${Env}-${Stack}-alb-ingress-frontend"
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref IdSecurityGroupInternet
      Subnets:
        - !Ref IdSubnetPublicIngress1A
        - !Ref IdSubnetPublicIngress1C
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: false
      Tags:
        - Key: Env
          Value: !Ref Env
        - Key: Stack
          Value: !Ref Stack
        - Key: Owner
          Value: !Ref Owner
        - Key: Cost
          Value: !Ref Cost

  TargetGroupFrontend:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub "${Env}-${Stack}-target-group-frontend"
      Port: 80
      Protocol: HTTP
      TargetType: ip
      HealthCheckIntervalSeconds: 15
      HealthCheckPath: /healthcheck
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 2
      Matcher: 
        HttpCode: 200
      VpcId: !Ref IdVpc
      Tags:
        - Key: Env
          Value: !Ref Env
        - Key: Stack
          Value: !Ref Stack
        - Key: Owner
          Value: !Ref Owner
  
  ListenerFrontend:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
        DefaultActions: 
          - TargetGroupArn: !Ref TargetGroupFrontend
            Type: forward
        LoadBalancerArn: !Ref AlbFrontend
        Port: 80
        Protocol: HTTP
